import type { Product } from "@/types"

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Kawaii Bunny Plushie",
    price: 28.99,
    image: "/cute-kawaii-crochet-animals-cats-bunnies-bears.jpg",
    category: "Animals",
    rating: 5,
    reviews: 124,
  },
  {
    id: 2,
    name: "Pastel Dragon",
    price: 45.99,
    image: "/crochet-fantasy-creatures-dragons-unicorns-magical.jpg",
    category: "Fantasy",
    rating: 5,
    reviews: 98,
  },
  {
    id: 3,
    name: "Kawaii Food Set",
    price: 32.99,
    image: "/kawaii-food-crochet-characters-cute-faces.jpg",
    category: "Food",
    rating: 5,
    reviews: 156,
  },
  {
    id: 4,
    name: "Anime Character",
    price: 55.99,
    image: "/crochet-anime-characters-manga-style-amigurumi.jpg",
    category: "Anime",
    rating: 5,
    reviews: 203,
  },
]

export const DETAILED_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Kawaii Cat Bundle",
    description: "Adorable cats with different expressions and accessories. Perfect for cat lovers! Each piece is lovingly handmade with premium yarn and endless care.",
    price: "$45-65",
    image: "/cute-kawaii-crochet-animals-cats-bunnies-bears.jpg",
    images: [
      "/cute-kawaii-crochet-animals-cats-bunnies-bears.jpg",
      "/cute-kawaii-crochet-animals-cats-bunnies-bears.jpg",
      "/cute-kawaii-crochet-animals-cats-bunnies-bears.jpg",
    ],
    category: "Kawaii Animals",
    difficulty: "Beginner",
    estimatedTimeHours: 8,
    rating: 5,
    reviews: 124,
    materials: ["Premium acrylic yarn", "Safety eyes", "Polyester stuffing", "Embroidery thread"],
    dimensions: "4-6 inches tall",
    features: ["Multiple expressions", "Cute accessories", "Soft pastel colors", "Machine washable"],
    tags: ["kawaii", "cat", "beginner-friendly", "gift-idea"],
  },
  {
    id: 2,
    name: "Anime Character Commission",
    description: "Your favorite anime character brought to life in crochet form! Detailed features and character accuracy guaranteed.",
    price: "$75-95",
    image: "/crochet-anime-characters-manga-style-amigurumi.jpg",
    images: [
      "/crochet-anime-characters-manga-style-amigurumi.jpg",
      "/crochet-anime-characters-manga-style-amigurumi.jpg",
      "/crochet-anime-characters-manga-style-amigurumi.jpg",
    ],
    category: "Anime Characters",
    difficulty: "Advanced",
    estimatedTimeHours: 16,
    rating: 5,
    reviews: 98,
    materials: ["Premium acrylic yarn", "Wire armature", "Safety eyes", "Polyester stuffing"],
    dimensions: "6-8 inches tall",
    features: ["Custom design", "Detailed features", "Character accuracy", "Poseable arms"],
    tags: ["anime", "custom", "advanced", "character"],
  },
  {
    id: 3,
    name: "Magical Dragon",
    description: "Mystical dragons with wings, scales, and magical details. Each dragon is unique with poseable wings.",
    price: "$85-95",
    image: "/crochet-fantasy-creatures-dragons-unicorns-magical.jpg",
    images: [
      "/crochet-fantasy-creatures-dragons-unicorns-magical.jpg",
      "/crochet-fantasy-creatures-dragons-unicorns-magical.jpg",
      "/crochet-fantasy-creatures-dragons-unicorns-magical.jpg",
    ],
    category: "Fantasy Creatures",
    difficulty: "Expert",
    estimatedTimeHours: 20,
    rating: 5,
    reviews: 76,
    materials: ["Premium acrylic yarn", "Wire armature", "Safety eyes", "Felt details", "Metallic thread"],
    dimensions: "8-12 inches wingspan",
    features: ["Poseable wings", "Detailed scales", "Magical accessories", "Wire armature for stability"],
    tags: ["fantasy", "dragon", "expert", "poseable"],
  },
  {
    id: 4,
    name: "Kawaii Food Friends",
    description: "Cute food characters with happy faces and kawaii charm! Perfect for kitchen decor or gifts.",
    price: "$35-55",
    image: "/kawaii-food-crochet-characters-cute-faces.jpg",
    images: [
      "/kawaii-food-crochet-characters-cute-faces.jpg",
      "/kawaii-food-crochet-characters-cute-faces.jpg",
      "/kawaii-food-crochet-characters-cute-faces.jpg",
    ],
    category: "Food Characters",
    difficulty: "Beginner",
    estimatedTimeHours: 6,
    rating: 5,
    reviews: 156,
    materials: ["Premium acrylic yarn", "Safety eyes", "Polyester stuffing", "Embroidery thread"],
    dimensions: "3-5 inches",
    features: ["Happy expressions", "Food accuracy", "Kawaii style", "Lightweight"],
    tags: ["kawaii", "food", "beginner-friendly", "cute"],
  },
  {
    id: 5,
    name: "Custom Design",
    description: "Bring your unique idea to life! Send me your concept and I'll create it with collaborative design process.",
    price: "$65-120",
    image: "/custom-crochet-design-sketch-to-reality.jpg",
    images: [
      "/custom-crochet-design-sketch-to-reality.jpg",
      "/custom-crochet-design-sketch-to-reality.jpg",
      "/custom-crochet-design-sketch-to-reality.jpg",
    ],
    category: "Custom Design",
    difficulty: "Varies",
    estimatedTimeHours: 12,
    rating: 5,
    reviews: 203,
    materials: ["Premium materials based on design", "Custom color selection", "Specialty yarns available"],
    dimensions: "Custom sizing",
    features: ["Your concept", "Collaborative design", "Unlimited revisions", "Progress photos"],
    tags: ["custom", "personalized", "unique", "collaborative"],
  },
  {
    id: 6,
    name: "Holiday Specials",
    description: "Seasonal characters perfect for holidays and special occasions. Festive accessories and holiday colors.",
    price: "$45-75",
    image: "/holiday-themed-crochet-characters-seasonal.jpg",
    images: [
      "/holiday-themed-crochet-characters-seasonal.jpg",
      "/holiday-themed-crochet-characters-seasonal.jpg",
      "/holiday-themed-crochet-characters-seasonal.jpg",
    ],
    category: "Holiday Themed",
    difficulty: "Intermediate",
    estimatedTimeHours: 10,
    rating: 5,
    reviews: 89,
    materials: ["Premium acrylic yarn", "Seasonal fabrics", "Safety eyes", "Festive embellishments"],
    dimensions: "5-7 inches tall",
    features: ["Seasonal themes", "Holiday colors", "Festive accessories", "Gift-ready packaging"],
    tags: ["holiday", "seasonal", "festive", "gift"],
  },
]
